name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNWI1OGM2YzMtMThhYS00NGZhLTlhYTItYjBiYmE0YWRhZDgwIiwidGVuYW50X2lkIjoiOWQ2Y2Y3OTk5YTlkMDhmYTI3Yzc2Yzg2M2YyNTc2NWIyNmNjZTE0YTFmOGNkZTU5MDZkNTFiNWM4M2VhYmNmYSIsImludGVybmFsX3NlY3JldCI6IjM4MzQwNWI4LTgyMWItNDEwYy04NTE4LTJmMjAzOWE1NDdiMCJ9.ngP42qHDNY15BX9QxZsVprnwNdmM0y-6ur-4x4VPHuY"
DIRECT_URL = "postgresql://neondb_owner:ceV7rOH5wqWa@ep-royal-truth-a1zi3lor.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"
JWT_SECRET = "secret"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1